#############################################################################
# Makefile for building: GEMUFF
# Generated by qmake (2.01a) (Qt 4.8.4) on: Mon Mar 31 17:24:55 2014
# Project:  GEMUFF.pro
# Template: app
# Command: /usr/bin/qmake-qt4 -spec /usr/lib64/qt4/mkspecs/linux-g++ -o Makefile GEMUFF.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_DECLARATIVE_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/lib64/qt4/mkspecs/linux-g++ -I. -I/usr/include/QtCore -I/usr/include/QtGui -I/usr/include/QtDeclarative -I/usr/include -I/opt/local/include -I/usr/local/include -I/usr/include/ffmpeg -I/usr/local/cuda-5.5/include -I/usr/local/cuda-5.5/samples/common/inc -I. -I.
LINK          = g++
LFLAGS        = -Wl,-rpath,/usr/local/cuda/lib -Wl,-O1 -Wl,-z,relro
LIBS          = $(SUBLIBS)  -L/opt/local/lib -L/usr/local/lib -L/lib64 -L/usr/lib64 -lavcodec -lavformat -lswscale -lavutil -lssl -lcrypto -lopencv_core -lopencv_highgui -lopencv_imgproc -lopencv_gpu -lboost_filesystem -lboost_system -lcudart -lQtDeclarative -lQtScript -lQtSvg -lQtSql -lQtXmlPatterns -lQtNetwork -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake-qt4
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = 
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp \
		video.cpp \
		imageregister.cpp \
		player.cpp \
		diffplayer.cpp \
		helperfunctions.cpp \
		diffalgorithms.cpp \
		hash.cpp \
		image.cpp \
		Operations.cpp moc_mainwindow.cpp
OBJECTS       = ${OBJECTS_DIR}K_IMUFF_cuda.o \
		main.o \
		mainwindow.o \
		video.o \
		imageregister.o \
		player.o \
		diffplayer.o \
		helperfunctions.o \
		diffalgorithms.o \
		hash.o \
		image.o \
		Operations.o \
		moc_mainwindow.o
DIST          = /usr/lib64/qt4/mkspecs/common/unix.conf \
		/usr/lib64/qt4/mkspecs/common/linux.conf \
		/usr/lib64/qt4/mkspecs/common/gcc-base.conf \
		/usr/lib64/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/lib64/qt4/mkspecs/common/g++-base.conf \
		/usr/lib64/qt4/mkspecs/common/g++-unix.conf \
		/usr/lib64/qt4/mkspecs/qconfig.pri \
		/usr/lib64/qt4/mkspecs/features/qt_functions.prf \
		/usr/lib64/qt4/mkspecs/features/qt_config.prf \
		/usr/lib64/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/lib64/qt4/mkspecs/features/default_pre.prf \
		/usr/lib64/qt4/mkspecs/features/release.prf \
		/usr/lib64/qt4/mkspecs/features/default_post.prf \
		/usr/lib64/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/lib64/qt4/mkspecs/features/warn_on.prf \
		/usr/lib64/qt4/mkspecs/features/qt.prf \
		/usr/lib64/qt4/mkspecs/features/unix/thread.prf \
		/usr/lib64/qt4/mkspecs/features/moc.prf \
		/usr/lib64/qt4/mkspecs/features/resources.prf \
		/usr/lib64/qt4/mkspecs/features/uic.prf \
		/usr/lib64/qt4/mkspecs/features/yacc.prf \
		/usr/lib64/qt4/mkspecs/features/lex.prf \
		/usr/lib64/qt4/mkspecs/features/include_source_dir.prf \
		GEMUFF.pro
QMAKE_TARGET  = GEMUFF
DESTDIR       = 
TARGET        = GEMUFF

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_mainwindow.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: GEMUFF.pro  /usr/lib64/qt4/mkspecs/linux-g++/qmake.conf /usr/lib64/qt4/mkspecs/common/unix.conf \
		/usr/lib64/qt4/mkspecs/common/linux.conf \
		/usr/lib64/qt4/mkspecs/common/gcc-base.conf \
		/usr/lib64/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/lib64/qt4/mkspecs/common/g++-base.conf \
		/usr/lib64/qt4/mkspecs/common/g++-unix.conf \
		/usr/lib64/qt4/mkspecs/qconfig.pri \
		/usr/lib64/qt4/mkspecs/features/qt_functions.prf \
		/usr/lib64/qt4/mkspecs/features/qt_config.prf \
		/usr/lib64/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/lib64/qt4/mkspecs/features/default_pre.prf \
		/usr/lib64/qt4/mkspecs/features/release.prf \
		/usr/lib64/qt4/mkspecs/features/default_post.prf \
		/usr/lib64/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/lib64/qt4/mkspecs/features/warn_on.prf \
		/usr/lib64/qt4/mkspecs/features/qt.prf \
		/usr/lib64/qt4/mkspecs/features/unix/thread.prf \
		/usr/lib64/qt4/mkspecs/features/moc.prf \
		/usr/lib64/qt4/mkspecs/features/resources.prf \
		/usr/lib64/qt4/mkspecs/features/uic.prf \
		/usr/lib64/qt4/mkspecs/features/yacc.prf \
		/usr/lib64/qt4/mkspecs/features/lex.prf \
		/usr/lib64/qt4/mkspecs/features/include_source_dir.prf \
		/lib64/libQtDeclarative.prl \
		/lib64/libQtScript.prl \
		/lib64/libQtCore.prl \
		/lib64/libQtSvg.prl \
		/lib64/libQtGui.prl \
		/lib64/libQtSql.prl \
		/lib64/libQtXmlPatterns.prl \
		/lib64/libQtNetwork.prl
	$(QMAKE) -spec /usr/lib64/qt4/mkspecs/linux-g++ -o Makefile GEMUFF.pro
/usr/lib64/qt4/mkspecs/common/unix.conf:
/usr/lib64/qt4/mkspecs/common/linux.conf:
/usr/lib64/qt4/mkspecs/common/gcc-base.conf:
/usr/lib64/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/lib64/qt4/mkspecs/common/g++-base.conf:
/usr/lib64/qt4/mkspecs/common/g++-unix.conf:
/usr/lib64/qt4/mkspecs/qconfig.pri:
/usr/lib64/qt4/mkspecs/features/qt_functions.prf:
/usr/lib64/qt4/mkspecs/features/qt_config.prf:
/usr/lib64/qt4/mkspecs/features/exclusive_builds.prf:
/usr/lib64/qt4/mkspecs/features/default_pre.prf:
/usr/lib64/qt4/mkspecs/features/release.prf:
/usr/lib64/qt4/mkspecs/features/default_post.prf:
/usr/lib64/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/lib64/qt4/mkspecs/features/warn_on.prf:
/usr/lib64/qt4/mkspecs/features/qt.prf:
/usr/lib64/qt4/mkspecs/features/unix/thread.prf:
/usr/lib64/qt4/mkspecs/features/moc.prf:
/usr/lib64/qt4/mkspecs/features/resources.prf:
/usr/lib64/qt4/mkspecs/features/uic.prf:
/usr/lib64/qt4/mkspecs/features/yacc.prf:
/usr/lib64/qt4/mkspecs/features/lex.prf:
/usr/lib64/qt4/mkspecs/features/include_source_dir.prf:
/lib64/libQtDeclarative.prl:
/lib64/libQtScript.prl:
/lib64/libQtCore.prl:
/lib64/libQtSvg.prl:
/lib64/libQtGui.prl:
/lib64/libQtSql.prl:
/lib64/libQtXmlPatterns.prl:
/lib64/libQtNetwork.prl:
qmake:  FORCE
	@$(QMAKE) -spec /usr/lib64/qt4/mkspecs/linux-g++ -o Makefile GEMUFF.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/GEMUFF1.0.0 || $(MKDIR) .tmp/GEMUFF1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/GEMUFF1.0.0/ && $(COPY_FILE) --parents K_IMUFF.cu .tmp/GEMUFF1.0.0/ && $(COPY_FILE) --parents mainwindow.h K_IMUFF.h video.h imageregister.h player.h diffplayer.h helperfunctions.h GEMUFF.h diffalgorithms.h hash.h image.h Operations.h diff2data.h .tmp/GEMUFF1.0.0/ && $(COPY_FILE) --parents main.cpp mainwindow.cpp video.cpp imageregister.cpp player.cpp diffplayer.cpp helperfunctions.cpp diffalgorithms.cpp hash.cpp image.cpp Operations.cpp .tmp/GEMUFF1.0.0/ && $(COPY_FILE) --parents mainwindow.ui .tmp/GEMUFF1.0.0/ && (cd `dirname .tmp/GEMUFF1.0.0` && $(TAR) GEMUFF1.0.0.tar GEMUFF1.0.0 && $(COMPRESS) GEMUFF1.0.0.tar) && $(MOVE) `dirname .tmp/GEMUFF1.0.0`/GEMUFF1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/GEMUFF1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_cuda_make_all: ${OBJECTS_DIR}K_IMUFF_cuda.o
compiler_cuda_clean:
	-$(DEL_FILE) ${OBJECTS_DIR}K_IMUFF_cuda.o
${OBJECTS_DIR}K_IMUFF_cuda.o: K_IMUFF.cu
	/usr/local/cuda/bin/nvcc -c -arch sm_12 -I "/opt/local/include" -I "/usr/local/include" -I "/usr/include/ffmpeg" -I "/usr/local/cuda/include" -I "/usr/local/cuda/samples/common/inc" K_IMUFF.cu -o ${OBJECTS_DIR}K_IMUFF_cuda.o

compiler_moc_header_make_all: moc_mainwindow.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp
moc_mainwindow.cpp: video.h \
		imageregister.h \
		hash.h \
		GEMUFF.h \
		image.h \
		K_IMUFF.h \
		diffplayer.h \
		player.h \
		diff2data.h \
		mainwindow.h
	/usr/lib64/qt4/bin/moc $(DEFINES) $(INCPATH) mainwindow.h -o moc_mainwindow.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h
ui_mainwindow.h: mainwindow.ui
	/usr/lib64/qt4/bin/uic mainwindow.ui -o ui_mainwindow.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_cuda_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp mainwindow.h \
		video.h \
		imageregister.h \
		hash.h \
		GEMUFF.h \
		image.h \
		K_IMUFF.h \
		diffplayer.h \
		player.h \
		diff2data.h \
		diffalgorithms.h \
		helperfunctions.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		video.h \
		imageregister.h \
		hash.h \
		GEMUFF.h \
		image.h \
		K_IMUFF.h \
		diffplayer.h \
		player.h \
		diff2data.h \
		ui_mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

video.o: video.cpp video.h \
		imageregister.h \
		hash.h \
		GEMUFF.h \
		image.h \
		K_IMUFF.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o video.o video.cpp

imageregister.o: imageregister.cpp imageregister.h \
		hash.h \
		GEMUFF.h \
		image.h \
		K_IMUFF.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o imageregister.o imageregister.cpp

player.o: player.cpp player.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o player.o player.cpp

diffplayer.o: diffplayer.cpp diffplayer.h \
		player.h \
		diff2data.h \
		hash.h \
		GEMUFF.h \
		image.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o diffplayer.o diffplayer.cpp

helperfunctions.o: helperfunctions.cpp helperfunctions.h \
		hash.h \
		GEMUFF.h \
		image.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o helperfunctions.o helperfunctions.cpp

diffalgorithms.o: diffalgorithms.cpp diffalgorithms.h \
		helperfunctions.h \
		hash.h \
		GEMUFF.h \
		image.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o diffalgorithms.o diffalgorithms.cpp

hash.o: hash.cpp hash.h \
		GEMUFF.h \
		image.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o hash.o hash.cpp

image.o: image.cpp image.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o image.o image.cpp

Operations.o: Operations.cpp Operations.h \
		video.h \
		imageregister.h \
		hash.h \
		GEMUFF.h \
		image.h \
		K_IMUFF.h \
		diff2data.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Operations.o Operations.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

